define(["jquery","../device/index","../css3animate/index"],function(a,b,c){'use strict';function d(b){if("string"==typeof b)return a(b);if(b instanceof a){if(1==b.length)return b[0];var c=[];b.each(function(){c.push(a(this)[0])}),b=c}return b}//各种需要用到的函数
function e(){var c=h();c.hasscroll?(a("#lock").css({overflowY:"scroll"}),a("html").css({overflow:"hidden"}),a("html").css({marginRight:c.vertical})):(a("#lock").css({overflowY:"hidden",zIndex:self.curZindex}),a("html").css({overflow:"hidden"})),b.isMobile&&document.addEventListener("touchmove",g,!1)}function f(){a("html").css({overflow:window.Popup_curhtmlOverFlow}),a("html").css({marginRight:0}),b.isMobile&&document.removeEventListener("touchmove",g)}function g(a){a.preventDefault()}function h(){var c=a(window).height();if(b.isMobile||!("hidden"!=document.body.style.overflow&&"no"!=document.body.scroll&&document.body.scrollHeight>c))return{vertical:0,hasscroll:!1};if(n)return n;var d=document.createElement("div");// if MSIE
// 如此设置的话，scroll bar的最大宽度不能大于100px（通常不会）。
return d.style.cssText="overflow:scroll;width:100px;height:100px;",document.body.appendChild(d),d&&(n={horizontal:d.offsetHeight-d.clientHeight,vertical:d.offsetWidth-d.clientHeight,hasscroll:!0}),document.body.removeChild(d),n}function i(a,b,c){return b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}a=a&&Object.prototype.hasOwnProperty.call(a,"default")?a["default"]:a,b=b&&Object.prototype.hasOwnProperty.call(b,"default")?b["default"]:b,c=c&&Object.prototype.hasOwnProperty.call(c,"default")?c["default"]:c;var j,k="undefined"==typeof globalThis?"undefined"==typeof window?"undefined"==typeof global?"undefined"==typeof self?{}:self:global:window:globalThis,l=function(a,b){return b={exports:{}},a(b,b.exports),b.exports}(function(a){(function(b,c){a.exports=c()})("undefined"==typeof window?k:window,function(){/**
	     * Iterate over each of the provided element(s).
	     *
	     * @param {HTMLElement|HTMLElement[]} elements
	     * @param {Function}                  callback
	     */function a(a,b){var c=Object.prototype.toString.call(a),d="[object Array]"===c||"[object NodeList]"===c||"[object HTMLCollection]"===c||"[object Object]"===c||"undefined"!=typeof jQuery&&a instanceof jQuery||//jquery
"undefined"!=typeof Elements&&a instanceof Elements,e=0,f=a.length;if(d)for(;e<f;e++)b(a[e]);else b(a)}/**
	     * Get element size
	     * @param {HTMLElement} element
	     * @returns {Object} {width, height}
	     */function b(a){var b=Math.round;if(!a.getBoundingClientRect)return{width:a.offsetWidth,height:a.offsetHeight};var c=a.getBoundingClientRect();return{width:b(c.width),height:b(c.height)}}/**
	     * Class for dimension change detection.
	     *
	     * @param {Element|Element[]|Elements|jQuery} element
	     * @param {Function} callback
	     *
	     * @constructor
	     */ // Make sure it does not throw in a SSR (Server Side Rendering) situation
if("undefined"==typeof window)return null;// Only used for the dirty checking, so the event callback count is limited to max 1 call per fps per sensor.
// In combination with the event based resize sensor this saves cpu time, because the sensor is too fast and
// would generate too many unnecessary events.
var c=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,20)},d=function(e,f){/**
	         *
	         * @constructor
	         */function g(){var a=[];this.add=function(b){a.push(b)};var b,c;this.call=function(d){for(b=0,c=a.length;b<c;b++)a[b].call(this,d)},this.remove=function(d){var e=[];for(b=0,c=a.length;b<c;b++)a[b]!==d&&e.push(a[b]);a=e},this.length=function(){return a.length}}/**
	         *
	         * @param {HTMLElement} element
	         * @param {Function}    resized
	         */function h(a,d){if(a){if(a.resizedAttached)return void a.resizedAttached.add(d);a.resizedAttached=new g,a.resizedAttached.add(d),a.resizeSensor=document.createElement("div"),a.resizeSensor.dir="ltr",a.resizeSensor.className="resize-sensor";var e="position: absolute; left: 0; top: 0; transition: 0s;";a.resizeSensor.style.cssText="position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden; max-width: 100%",a.resizeSensor.innerHTML="<div class=\"resize-sensor-expand\" style=\"position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden; max-width: 100%\"><div style=\""+e+"\"></div></div><div class=\"resize-sensor-shrink\" style=\"position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden; max-width: 100%\"><div style=\""+e+" width: 200%; height: 200%\"></div></div>",a.appendChild(a.resizeSensor);var f=window.getComputedStyle(a),h=f?f.getPropertyValue("position"):null;"absolute"!==h&&"relative"!==h&&"fixed"!==h&&(a.style.position="relative");var i,j,k,l=a.resizeSensor.childNodes[0],m=l.childNodes[0],n=a.resizeSensor.childNodes[1],o=b(a),p=o.width,q=o.height,r=!0,s=function(){m.style.width="100000px",m.style.height="100000px",l.scrollLeft=1e5,l.scrollTop=1e5,n.scrollLeft=1e5,n.scrollTop=1e5},t=function(){// Check if element is hidden
if(r){if(!l.scrollTop&&!l.scrollLeft)return s(),void(k||(k=c(function(){k=0,t()})));r=!1}s()};a.resizeSensor.resetSensor=t;var u=function(){j=0,i&&(p=o.width,q=o.height,a.resizedAttached&&a.resizedAttached.call(o))},v=function(){o=b(a),i=o.width!==p||o.height!==q,i&&!j&&(j=c(u)),t()},w=function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,c)};w(l,"scroll",v),w(n,"scroll",v),c(t)}}var i;"undefined"==typeof ResizeObserver?a(e,function(a){h(a,f)}):(i=new ResizeObserver(function(b){a(b,function(a){f.call(this,{width:a.contentRect.width,height:a.contentRect.height})})}),void 0!==e&&a(e,function(a){i.observe(a)})),this.detach=function(b){"undefined"==typeof ResizeObserver?d.detach(e,b):a(e,function(a){i.unobserve(a)})},this.reset=function(){e.resizeSensor.resetSensor()}};return d.reset=function(b){a(b,function(a){a.resizeSensor.resetSensor()})},d.detach=function(b,c){a(b,function(a){!a||a.resizedAttached&&"function"==typeof c&&(a.resizedAttached.remove(c),a.resizedAttached.length())||a.resizeSensor&&(a.contains(a.resizeSensor)&&a.removeChild(a.resizeSensor),delete a.resizeSensor,delete a.resizedAttached)})},d})}),m=function(g,h){function i(b){var c=Math.abs;if(b=a(b),!!b.css("max-height"))return!1;var d=b.height(),e=a("<div style=\"position:relative;width:100%;height:10px;\"></div>");b.append(e);var f=b.height();e.remove();return 5>=c(f-d-10)}if(g=d(g),!!g){g=a(g),window.Popup_curhtmlOverFlow||(window.Popup_curhtmlOverFlow=a("html").css("overflow"));var k={animation:b.support_css3("transform")?"scale":"fade",time:300,video:null,//内嵌的视频对象
auto:!0,padding:20,//弹窗距离上下的距离
replace:!0,//窗口模式 replaceF 表示当已经有一个窗口打开时，将会替换当前窗口
zIndex:3e3,scrollObj:"this",opacity:.85,fixbody:!0,autoCenter:!0,closeOnClickModal:!0,startShow:function(){},endShow:function(){},startHide:function(){},endHide:function(){}};h=a.extend(k,h);var m=this;m.animation=h.animation,m.curCover=[],m.curZindex=h.zIndex,m.time=h.time,m.scrollArray={},"undefined"==typeof window.Popupcoverid&&(window.Popupcoverid=0),m.init=function(){1>a("#overlay").length&&a("body").append("<div style='position: fixed!important;_position:fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: "+m.curZindex+"; background: rgb(0, 0, 0);display:none;' id='overlay'><div style='position: fixed!important;_position:fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 0;display:block;overflow-y:scroll' id='lock'></div></div>"),m.setCoverInit(),m.bind()},this.setCoverInit=function(){g.each(function(){a(this).css({display:"block",opacity:0,top:"10000%"}),a(this).css({zIndex:m.curZindex,left:"50%",marginTop:-a(this).outerWidth()/2+"px",marginLeft:-a(this).outerWidth()/2+"px"}),a(this).attr("data-state","hide"),a(this).attr("data-gcoverid",window.Popupcoverid++)}),g.css({position:"fixed"})},this.setVideo=function(a){h.video=a},this.bind=function(){a(window).bind("resize",function(){setTimeout(function(){for(var a in m.curCover)m.setCover(m.curCover[a])},10)}),g.each(function(){//绑定 close 和confirm 关闭弹窗
var b=a(this);// console.log($(this).find(".close,.confirm,.Popup_close"));
a(this).find(".close,.confirm,.Popup_close").unbind("click").bind("click",function(a){a.stopPropagation(),m.hide(b)})}),!h.closeOnClickModal||a("#overlay").click(function(){m.hide()})},this.setScroll=function(c,d){// console.log(isAutoHeight(obj));
if(j=document.body.clientHeight,d.addClass("Popup_SCROLLER"),!i(c))c.css({overflow:"auto"});else if(d.css({height:"auto",maxHeight:"none"}),j=a(window).height(),d.outerHeight()>j-2*h.padding){var e=d.outerHeight()-d.height(),f=j-2*h.padding-e;0>f&&(f=.1*j),d.css({maxHeight:f}),d.css({overflow:"auto"})}// if (typeof scrollobj.data('Popupcoverid') == 'undefined' && scrollobj.height() > obj.height()) {
//     scrollobj.height(obj.height());
// }
if(b.isPc);else{d.css({"-webkit-overflow-scrolling":"touch"});var g,k;b.isMobile&&"undefined"==typeof d.data("bindEvent")&&(d[0].addEventListener("touchstart",function(a){g=a.changedTouches[0].pageY}),d[0].addEventListener("touchmove",function(a){k=a.changedTouches[0].pageY,0<k-g?0<d.scrollTop()&&a.stopPropagation():d.scrollTop()+d.height()<d[0].scrollHeight&&a.stopPropagation(),g=k}),d.attr("data-bindEvent",!0))}},this.setCover=function(b){//窗口变化是改变当前弹窗的样式
if("undefined"!=typeof b&&b&&"hide"!=b.attr("data-state")){var c;j=document.body.clientHeight,b.each(function(){if(!h.scrollObj)a(this).css({overflow:"visible"});else//容许出滚动条
if("this"==h.scrollObj){var b=a(this).find(".scroller");0==b.length&&(b=a(this)),m.setScroll(a(this),b)}else m.setScroll(a(this),a(this).find(h.scrollObj));c=a(this).outerHeight(),a(this).css({top:"50%",left:"50%",marginTop:-c/2,marginLeft:-a(this).outerWidth()/2})})}},this.resize=function(a,b){a.css(b)},this.show=function(e,f,i,j){if(e=a(d(e)),"object"==typeof e&&e||1!=g.length||("function"==typeof e&&(j=e),"number"==typeof e&&(!!f&&(j=f),f=null,i=e),"string"==typeof e&&(!!i&&(j=i),!!f&&(i=f),f=e),e=g),"object"==typeof e&&e&&"show"!=e.attr("data-state")&&"showing"!=e.attr("data-state")){"function"==typeof f?(j=f,f=m.animation):("undefined"==typeof f||!f)&&(f=m.animation),"function"==typeof i?(j=i,i=m.time):("undefined"==typeof i||!i)&&(i=m.time);var k=function(){e.each(function(){if(!a(this).data("resizesensor")){var b=this;a(this).attr("data-resizesensor",1),!h.autoCenter||new l(a(this)[0],function(){m.setCover(a(b))})}}),e.attr("data-state","show"),h.endShow(e),"function"==typeof j&&j()};h.startShow(e),h.auto&&h.video&&h.video.play(),e.attr("data-state","showing"),e.attr("data-animation",f),m.setCover(e),m.curCover.push(e),m.showoverlay(i),1<m.curCover.length&&h.replace&&m.hide(m.curCover[m.curCover.length-2],f),m.curZindex++,b.isIe7?(e.stop().css({zIndex:m.curZindex,opacity:1,display:"block",marginLeft:-e.outerWidth()/2+"px",marginTop:-e.outerHeight()/2+"px"}),k()):"fade"==f?e.stop().css({zIndex:m.curZindex,opacity:1,display:"block",marginLeft:-e.outerWidth()/2+"px",marginTop:-e.outerHeight()/2+"px"}).animate({opacity:1,display:"block"},i,"swing",function(){k()}):"fadedown"==f?e.css({zIndex:m.curZindex,marginTop:-e.outerHeight()/2-150+"px",marginLeft:-e.outerWidth()/2+"px",opacity:0,display:"block"}).stop().animate({marginTop:-e.outerHeight()/2+"px",opacity:1},i,"swing",function(){k()}):"fadeup"==f?e.css({zIndex:m.curZindex,marginTop:-e.outerHeight()/2+150+"px",marginLeft:-e.outerWidth()/2+"px",opacity:0,display:"block"}).stop().animate({marginTop:-e.outerHeight()/2+"px",opacity:1},i,"swing",function(){k()}):"scale"==f&&(e.stop(),c.set(e,{zIndex:m.curZindex,marginTop:-e.outerHeight()/2+"px",marginLeft:-e.outerWidth()/2+"px",opacity:0,top:"50%",left:"50%",scale:.5,display:"block"}),c.to(e,{marginTop:-e.outerHeight()/2+"px",opacity:1,scale:1},i,"ease-in-out",function(){k()}))}//缺省obj后面的各种参数
},this.hide=function(d,e,f,g){if(!d&&0<m.curCover.length){for(var j in m.curCover)console.log(m.curCover[j]),m.hide(m.curCover[j],e,f,g);return}if("undefined"!=typeof d&&d&&"hide"!=d.attr("data-state")&&"hiding"!=d.attr("data-state")){d=a(d),"function"==typeof e&&(g=e,e=void 0),"undefined"!=typeof e&&e||("undefined"==typeof d.data("animation")?e=m.animation:e=d.data("animation")),"function"==typeof f?(g=f,f=m.time):("undefined"==typeof f||!f)&&(f=m.time),d.attr("data-state","hiding");var k=function(){d.attr("data-state","hide"),"function"==typeof g&&g(),h.video&&h.video.stop(),h.endHide(d)};for(var j in h.startHide(d),m.curZindex--,b.isIe7?(d.stop().hide(),k()):"fade"==e?d.stop().animate({opacity:0},.6*f,"swing",function(){d.css({top:"1000%"}),k()}):"fadedown"==e?d.each(function(){var b=a(this);a(this).stop().animate({marginTop:-a(this).outerHeight()/2-150+"px",opacity:0},f,"swing",function(){b.css({top:"1000%"}),k()})}):"fadeup"==e?d.each(function(){var b=a(this);a(this).stop().animate({marginTop:-a(this).outerHeight()/2+150+"px",opacity:0},f,"swing",function(){b.css({top:"1000%"}),k()})}):"scale"==e&&d.each(function(){var b=a(this);a(this).stop(),c.to(this,{scale:.5,opacity:0},f,"ease-in-out",function(){b.css({top:"1000%",display:"none"}),k()})}),m.hideoverlay(f),m.curCover)if(d.data("Popupcoverid")==m.curCover[j].data("Popupcoverid")){m.curCover.splice(j,1);break}}},this.showoverlay=function(b){if(!m.overclock||(clearTimeout(m.overclock),m.overclock=null),m.curZindex++,1<m.curCover.length)a("#overlay").css({zIndex:m.curZindex});else{if("none"==a("#overlay").css("display")&&a("#overlay").css({opacity:"0",display:"block"}),a("#overlay").css({zIndex:m.curZindex}),a("#overlay").stop().animate({opacity:h.opacity},b,function(){}),a("#lock").show(),!window.Popup_curhtmlOverFlow){var c=a("html").css("overflow"),d=a("body").css("overflow");window.Popup_curhtmlOverFlow=c,"hidden"!=d&&(window.Popup_curhtmlOverFlow=d)}!h.fixbody||e()}},this.hideoverlay=function(b){if(m.curZindex--,!m.overclock||(clearTimeout(m.overclock),m.overclock=null),1<m.curCover.length)m.overclock=setTimeout(function(){m.overclock=null,a("#overlay").css({zIndex:m.curZindex-1})},b);else{var c=function(){a("#overlay").css({display:"none",zIndex:m.curZindex-1}),!h.fixbody||f()};// if(DEVICE.isPc){
a("#overlay").stop().animate({opacity:0},b,c),a("#lock").css({overflowY:"hidden"}),a("#lock").fadeOut(b)}},this.init()}// console.log(coverEle);
},n=0;return i(m,"plugin",function(b){return!b||!b.fn||function(b){b.fn.fPopup=function(b){return new m(a(this),b)}}(b),m}),m});
