define(["jquery","../device","../prefix"],function(a,b,c){'use strict';a=a&&Object.prototype.hasOwnProperty.call(a,"default")?a["default"]:a,b=b&&Object.prototype.hasOwnProperty.call(b,"default")?b["default"]:b,c=c&&Object.prototype.hasOwnProperty.call(c,"default")?c["default"]:c;/**
	    @author:pengzai
	    @blog:http://pengzai.dev
	    @github:https://github.com/pengzai-dev
	**/var d=function(d){var e,f=!!document.createElement("audio"),g=1,h=this,i="",j=!1;d=a.extend({file:"",loop:!0,volume:1,autoplay:!0,onplay:function(){},onpause:function(){}},d),h.init=function(){var c=a("#SOUND_AUDIO"),e=a("body");if(0==e.length)return void a(function(){h.init()});if(0==c.length){var g=a("<div id=\"SOUND_AUDIO_outer\"></div>");g.css({position:"absolute",width:100,height:100,top:"-500%"}),e.append(g);var i;i=f?"<audio preload=\"auto\" id=\"SOUND_AUDIO\" class=\"SOUND_AUDIO\"></audio>":"<embed id=\"SOUND_AUDIO\"></embed>",g.append(i)}if(c=a("#SOUND_AUDIO"),h.audioElement=c[0],h.setAudio(),d.autoplay){function c(){h.play(),a(document).unbind("touchstart",c),a(document).unbind("mousedown",c)}//
if(b.isWeixin&&"object"!=typeof WeixinJSBridge)"undefined"==typeof WeixinJSBridgeReady&&(document.addEventListener?document.addEventListener("WeixinJSBridgeReady",function(){h.play()},!1):(a(document).bind("touchstart",c),a(document).bind("mousedown",c)));else try{h.audioElement.paused&&(h.audioElement.load(),h.audioElement.oncanplay=function(){h.play()},a(document).bind("touchstart",c),a(document).bind("mousedown",c))}catch(a){}}h.bind()},h.bind=function(){!h.audioElement||f&&(h.audioElement.addEventListener("playing",function(){"function"==typeof d.onplay&&d.onplay()},!1),h.audioElement.addEventListener("pause",function(){"function"==typeof d.onpause&&d.onpause()},!1),h.audioElement.addEventListener("ended",function(){"function"==typeof d.onpause&&d.onpause()},!1))},h.setAudio=function(b){"object"==typeof b&&(d=a.extend(d,b)),i!=d.file&&(SOUND_AUDIO.src=d.file,i=d.file),f?(d.loop?SOUND_AUDIO.loop="loop":SOUND_AUDIO.removeAttribute("loop"),d.autoplay?SOUND_AUDIO.autoplay="autoplay":SOUND_AUDIO.removeAttribute("autoplay"),SOUND_AUDIO.volume=d.volume,g=d.volume):(d.loop?SOUND_AUDIO.loop=!0:SOUND_AUDIO.removeAttribute("loop"),d.autoplay?SOUND_AUDIO.autoplay=!0:SOUND_AUDIO.removeAttribute("autostart"))},h.play=function(b){"object"==typeof b?(d=a.extend(d,b),h.setAudio()):"string"==typeof b&&(d.file=b,h.setAudio()),h.resume(),f||"function"!=typeof d.onplay||d.onplay(),e="play"},h.pause=function(a){h.audioElement&&((b.isiOS||!f)&&(a=!1),"undefined"==typeof a&&(a=!0),h.volumeclock&&(clearInterval(h.volumeclock),h.volumeclock=null),a?(g=h.audioElement.volume,h.volumeclock=setInterval(function(){return g-=.2,0>=g?(g=0,h.audioElement.volume=0,clearInterval(h.volumeclock),h.volumeclock=null,void h.audioElement.pause()):void(h.audioElement.volume=g)},100)):h.audioElement.pause(),!f&&"function"==typeof d.onpause&&d.onpause(),e="pause")},h.stop=function(a){h.pause(a),h.audioElement.load()},h.resume=function(){if(h.audioElement){if(!b.isiOS){h.volumeclock&&(clearInterval(h.volumeclock),h.volumeclock=null),g=h.audioElement.volume;try{h.audioElement.play()}catch(a){// console.log(error);
}h.volumeclock=setInterval(function(){return g+=.2,g>=d.volume?(h.audioElement.volume=d.volume,clearInterval(h.volumeclock),void(h.volumeclock=null)):void(h.audioElement.volume=g)},100)}else//self.audioElement.load();
h.audioElement.play();e="play"}},h.bindBackRun=function(){// if (DEVICE.isWeixin) {
// 	return;
// }
// Get Browser Specific Hidden Property
function a(a){return"undefined"==typeof document.hidden?a?a+"Hidden":"hidden":"hidden"}// Get Browser Specific Visibility State
function b(a){return a?a+"VisibilityState":"visibilityState"}// Get Browser Specific Event
function f(a){return a?a+"visibilitychange":"visibilitychange"}function g(){document[k]?"play"==e?(j=!0,h.pause(!0)):j=!1:j&&(console.log("\u91CD\u65B0\u64AD\u653E"),h.resume(!0))}if(!d.backrun){var i=c.js,k=a(i),b=b(i),f=f(i);// console.log(PREFIX);
document.addEventListener(f,g,!1),document.addEventListener("visibilitychange",g,!1)}},h.init()};return d});
