import $ from"jquery";import DEVICE from"../device";import PREFIX from"../prefix";/**
    @author:pengzai
    @blog:http://pengzai.dev
    @github:https://github.com/pengzai-dev
**/var BgSound=function(a){var b,c=!!document.createElement("audio"),d=1,e=this,f="",g=!1;a=$.extend({file:"",loop:!0,volume:1,autoplay:!0,onplay:function(){},onpause:function(){}},a),e.init=function(){var b=$("#SOUND_AUDIO"),d=$("body");if(0==d.length)return void $(function(){e.init()});if(0==b.length){var f=$("<div id=\"SOUND_AUDIO_outer\"></div>");f.css({position:"absolute",width:100,height:100,top:"-500%"}),d.append(f);var g;g=c?"<audio preload=\"auto\" id=\"SOUND_AUDIO\" class=\"SOUND_AUDIO\"></audio>":"<embed id=\"SOUND_AUDIO\"></embed>",f.append(g)}if(b=$("#SOUND_AUDIO"),e.audioElement=b[0],e.setAudio(),a.autoplay){function a(){e.play(),$(document).unbind("touchstart",a),$(document).unbind("mousedown",a)}//
if(DEVICE.isWeixin&&"object"!=typeof WeixinJSBridge)"undefined"==typeof WeixinJSBridgeReady&&(document.addEventListener?document.addEventListener("WeixinJSBridgeReady",function(){e.play()},!1):($(document).bind("touchstart",a),$(document).bind("mousedown",a)));else try{e.audioElement.paused&&(e.audioElement.load(),e.audioElement.oncanplay=function(){e.play()},$(document).bind("touchstart",a),$(document).bind("mousedown",a))}catch(a){}}e.bind()},e.bind=function(){!e.audioElement||c&&(e.audioElement.addEventListener("playing",function(){"function"==typeof a.onplay&&a.onplay()},!1),e.audioElement.addEventListener("pause",function(){"function"==typeof a.onpause&&a.onpause()},!1),e.audioElement.addEventListener("ended",function(){"function"==typeof a.onpause&&a.onpause()},!1))},e.setAudio=function(b){"object"==typeof b&&(a=$.extend(a,b)),f!=a.file&&(SOUND_AUDIO.src=a.file,f=a.file),c?(a.loop?SOUND_AUDIO.loop="loop":SOUND_AUDIO.removeAttribute("loop"),a.autoplay?SOUND_AUDIO.autoplay="autoplay":SOUND_AUDIO.removeAttribute("autoplay"),SOUND_AUDIO.volume=a.volume,d=a.volume):(a.loop?SOUND_AUDIO.loop=!0:SOUND_AUDIO.removeAttribute("loop"),a.autoplay?SOUND_AUDIO.autoplay=!0:SOUND_AUDIO.removeAttribute("autostart"))},e.play=function(d){"object"==typeof d?(a=$.extend(a,d),e.setAudio()):"string"==typeof d&&(a.file=d,e.setAudio()),e.resume(),c||"function"!=typeof a.onplay||a.onplay(),b="play"},e.pause=function(f){e.audioElement&&((DEVICE.isiOS||!c)&&(f=!1),"undefined"==typeof f&&(f=!0),e.volumeclock&&(clearInterval(e.volumeclock),e.volumeclock=null),f?(d=e.audioElement.volume,e.volumeclock=setInterval(function(){return d-=.2,0>=d?(d=0,e.audioElement.volume=0,clearInterval(e.volumeclock),e.volumeclock=null,void e.audioElement.pause()):void(e.audioElement.volume=d)},100)):e.audioElement.pause(),!c&&"function"==typeof a.onpause&&a.onpause(),b="pause")},e.stop=function(a){e.pause(a),e.audioElement.load()},e.resume=function(){if(e.audioElement){if(!DEVICE.isiOS){e.volumeclock&&(clearInterval(e.volumeclock),e.volumeclock=null),d=e.audioElement.volume;try{e.audioElement.play()}catch(a){// console.log(error);
}e.volumeclock=setInterval(function(){return d+=.2,d>=a.volume?(e.audioElement.volume=a.volume,clearInterval(e.volumeclock),void(e.volumeclock=null)):void(e.audioElement.volume=d)},100)}else//self.audioElement.load();
e.audioElement.play();b="play"}},e.bindBackRun=function(){// if (DEVICE.isWeixin) {
// 	return;
// }
// Get Browser Specific Hidden Property
function c(a){return"undefined"==typeof document.hidden?a?a+"Hidden":"hidden":"hidden"}// Get Browser Specific Visibility State
function d(a){return a?a+"VisibilityState":"visibilityState"}// Get Browser Specific Event
function f(a){return a?a+"visibilitychange":"visibilitychange"}function h(){document[j]?"play"==b?(g=!0,e.pause(!0)):g=!1:g&&(console.log("\u91CD\u65B0\u64AD\u653E"),e.resume(!0))}if(!a.backrun){var i=PREFIX.js,j=c(i),d=d(i),f=f(i);// console.log(PREFIX);
document.addEventListener(f,h,!1),document.addEventListener("visibilitychange",h,!1)}},e.init()};export default BgSound;
