import $ from"jquery";import DEVICE from"../device/index";import Animate from"../css3animate/index";var commonjsGlobal="undefined"==typeof globalThis?"undefined"==typeof window?"undefined"==typeof global?"undefined"==typeof self?{}:self:global:window:globalThis;function createCommonjsModule(a,b){return b={exports:{}},a(b,b.exports),b.exports}var wh,resizeSensor=createCommonjsModule(function(a){/**
 * Copyright Marc J. Schmidt. See the LICENSE file at the top-level
 * directory of this distribution and at
 * https://github.com/marcj/css-element-queries/blob/master/LICENSE.
 */(function(b,c){a.exports=c()})("undefined"==typeof window?commonjsGlobal:window,function(){/**
     * Iterate over each of the provided element(s).
     *
     * @param {HTMLElement|HTMLElement[]} elements
     * @param {Function}                  callback
     */function a(a,b){var c=Object.prototype.toString.call(a),d="[object Array]"===c||"[object NodeList]"===c||"[object HTMLCollection]"===c||"[object Object]"===c||"undefined"!=typeof jQuery&&a instanceof jQuery||//jquery
"undefined"!=typeof Elements&&a instanceof Elements,e=0,f=a.length;if(d)for(;e<f;e++)b(a[e]);else b(a)}/**
     * Get element size
     * @param {HTMLElement} element
     * @returns {Object} {width, height}
     */function b(a){var b=Math.round;if(!a.getBoundingClientRect)return{width:a.offsetWidth,height:a.offsetHeight};var c=a.getBoundingClientRect();return{width:b(c.width),height:b(c.height)}}/**
     * Class for dimension change detection.
     *
     * @param {Element|Element[]|Elements|jQuery} element
     * @param {Function} callback
     *
     * @constructor
     */ // Make sure it does not throw in a SSR (Server Side Rendering) situation
if("undefined"==typeof window)return null;// Only used for the dirty checking, so the event callback count is limited to max 1 call per fps per sensor.
// In combination with the event based resize sensor this saves cpu time, because the sensor is too fast and
// would generate too many unnecessary events.
var c=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,20)},d=function(e,f){/**
         *
         * @constructor
         */function g(){var a=[];this.add=function(b){a.push(b)};var b,c;this.call=function(d){for(b=0,c=a.length;b<c;b++)a[b].call(this,d)},this.remove=function(d){var e=[];for(b=0,c=a.length;b<c;b++)a[b]!==d&&e.push(a[b]);a=e},this.length=function(){return a.length}}/**
         *
         * @param {HTMLElement} element
         * @param {Function}    resized
         */function h(a,d){if(a){if(a.resizedAttached)return void a.resizedAttached.add(d);a.resizedAttached=new g,a.resizedAttached.add(d),a.resizeSensor=document.createElement("div"),a.resizeSensor.dir="ltr",a.resizeSensor.className="resize-sensor";var e="position: absolute; left: 0; top: 0; transition: 0s;";a.resizeSensor.style.cssText="position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden; max-width: 100%",a.resizeSensor.innerHTML="<div class=\"resize-sensor-expand\" style=\"position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden; max-width: 100%\"><div style=\""+e+"\"></div></div><div class=\"resize-sensor-shrink\" style=\"position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden; max-width: 100%\"><div style=\""+e+" width: 200%; height: 200%\"></div></div>",a.appendChild(a.resizeSensor);var f=window.getComputedStyle(a),h=f?f.getPropertyValue("position"):null;"absolute"!==h&&"relative"!==h&&"fixed"!==h&&(a.style.position="relative");var i,j,k,l=a.resizeSensor.childNodes[0],m=l.childNodes[0],n=a.resizeSensor.childNodes[1],o=b(a),p=o.width,q=o.height,r=!0,s=function(){m.style.width="100000px",m.style.height="100000px",l.scrollLeft=1e5,l.scrollTop=1e5,n.scrollLeft=1e5,n.scrollTop=1e5},t=function(){// Check if element is hidden
if(r){if(!l.scrollTop&&!l.scrollLeft)return s(),void(k||(k=c(function(){k=0,t()})));r=!1}s()};a.resizeSensor.resetSensor=t;var u=function(){j=0,i&&(p=o.width,q=o.height,a.resizedAttached&&a.resizedAttached.call(o))},v=function(){o=b(a),i=o.width!==p||o.height!==q,i&&!j&&(j=c(u)),t()},w=function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,c)};w(l,"scroll",v),w(n,"scroll",v),c(t)}}var i;"undefined"==typeof ResizeObserver?a(e,function(a){h(a,f)}):(i=new ResizeObserver(function(b){a(b,function(a){f.call(this,{width:a.contentRect.width,height:a.contentRect.height})})}),void 0!==e&&a(e,function(a){i.observe(a)})),this.detach=function(b){"undefined"==typeof ResizeObserver?d.detach(e,b):a(e,function(a){i.unobserve(a)})},this.reset=function(){e.resizeSensor.resetSensor()}};return d.reset=function(b){a(b,function(a){a.resizeSensor.resetSensor()})},d.detach=function(b,c){a(b,function(a){!a||a.resizedAttached&&"function"==typeof c&&(a.resizedAttached.remove(c),a.resizedAttached.length())||a.resizeSensor&&(a.contains(a.resizeSensor)&&a.removeChild(a.resizeSensor),delete a.resizeSensor,delete a.resizedAttached)})},d})});//弹窗
function queryEle(a){if("string"==typeof a)return $(a);if(a instanceof $){if(1==a.length)return a[0];var b=[];a.each(function(){b.push($(this)[0])}),a=b}return a}var Popup=function(a,b){function c(a){var b=Math.abs;if(a=$(a),!!a.css("max-height"))return!1;var c=a.height(),d=$("<div style=\"position:relative;width:100%;height:10px;\"></div>");a.append(d);var e=a.height();d.remove();return 5>=b(e-c-10)}if(a=queryEle(a),!!a){a=$(a),window.Popup_curhtmlOverFlow||(window.Popup_curhtmlOverFlow=$("html").css("overflow"));var d={animation:DEVICE.support_css3("transform")?"scale":"fade",time:300,video:null,//内嵌的视频对象
auto:!0,padding:20,//弹窗距离上下的距离
replace:!0,//窗口模式 replaceF 表示当已经有一个窗口打开时，将会替换当前窗口
zIndex:3e3,scrollObj:"this",opacity:.85,fixbody:!0,autoCenter:!0,closeOnClickModal:!0,startShow:function(){},endShow:function(){},startHide:function(){},endHide:function(){}};b=$.extend(d,b);var e=this;e.animation=b.animation,e.curCover=[],e.curZindex=b.zIndex,e.time=b.time,e.scrollArray={},"undefined"==typeof window.Popupcoverid&&(window.Popupcoverid=0),e.init=function(){1>$("#overlay").length&&$("body").append("<div style='position: fixed!important;_position:fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: "+e.curZindex+"; background: rgb(0, 0, 0);display:none;' id='overlay'><div style='position: fixed!important;_position:fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 0;display:block;overflow-y:scroll' id='lock'></div></div>"),e.setCoverInit(),e.bind()},this.setCoverInit=function(){a.each(function(){$(this).css({display:"block",opacity:0,top:"10000%"}),$(this).css({zIndex:e.curZindex,left:"50%",marginTop:-$(this).outerWidth()/2+"px",marginLeft:-$(this).outerWidth()/2+"px"}),$(this).attr("data-state","hide"),$(this).attr("data-gcoverid",window.Popupcoverid++)}),a.css({position:"fixed"})},this.setVideo=function(a){b.video=a},this.bind=function(){$(window).bind("resize",function(){setTimeout(function(){for(var a in e.curCover)e.setCover(e.curCover[a])},10)}),a.each(function(){//绑定 close 和confirm 关闭弹窗
var a=$(this);// console.log($(this).find(".close,.confirm,.Popup_close"));
$(this).find(".close,.confirm,.Popup_close").unbind("click").bind("click",function(b){b.stopPropagation(),e.hide(a)})}),!b.closeOnClickModal||$("#overlay").click(function(){e.hide()})},this.setScroll=function(a,d){// console.log(isAutoHeight(obj));
if(wh=document.body.clientHeight,d.addClass("Popup_SCROLLER"),!c(a))a.css({overflow:"auto"});else if(d.css({height:"auto",maxHeight:"none"}),wh=$(window).height(),d.outerHeight()>wh-2*b.padding){var e=d.outerHeight()-d.height(),f=wh-2*b.padding-e;0>f&&(f=.1*wh),d.css({maxHeight:f}),d.css({overflow:"auto"})}// if (typeof scrollobj.data('Popupcoverid') == 'undefined' && scrollobj.height() > obj.height()) {
//     scrollobj.height(obj.height());
// }
if(DEVICE.isPc);else{d.css({"-webkit-overflow-scrolling":"touch"});var g,h;DEVICE.isMobile&&"undefined"==typeof d.data("bindEvent")&&(d[0].addEventListener("touchstart",function(a){g=a.changedTouches[0].pageY}),d[0].addEventListener("touchmove",function(a){h=a.changedTouches[0].pageY,0<h-g?0<d.scrollTop()&&a.stopPropagation():d.scrollTop()+d.height()<d[0].scrollHeight&&a.stopPropagation(),g=h}),d.attr("data-bindEvent",!0))}},this.setCover=function(a){//窗口变化是改变当前弹窗的样式
if("undefined"!=typeof a&&a&&"hide"!=a.attr("data-state")){var c;wh=document.body.clientHeight,a.each(function(){if(!b.scrollObj)$(this).css({overflow:"visible"});else//容许出滚动条
if("this"==b.scrollObj){var a=$(this).find(".scroller");0==a.length&&(a=$(this)),e.setScroll($(this),a)}else e.setScroll($(this),$(this).find(b.scrollObj));c=$(this).outerHeight(),$(this).css({top:"50%",left:"50%",marginTop:-c/2,marginLeft:-$(this).outerWidth()/2})})}},this.resize=function(a,b){a.css(b)},this.show=function(c,d,f,g){if(c=$(queryEle(c)),"object"==typeof c&&c||1!=a.length||("function"==typeof c&&(g=c),"number"==typeof c&&(!!d&&(g=d),d=null,f=c),"string"==typeof c&&(!!f&&(g=f),!!d&&(f=d),d=c),c=a),"object"==typeof c&&c&&"show"!=c.attr("data-state")&&"showing"!=c.attr("data-state")){"function"==typeof d?(g=d,d=e.animation):("undefined"==typeof d||!d)&&(d=e.animation),"function"==typeof f?(g=f,f=e.time):("undefined"==typeof f||!f)&&(f=e.time);var h=function(){c.each(function(){if(!$(this).data("resizesensor")){var a=this;$(this).attr("data-resizesensor",1),!b.autoCenter||new resizeSensor($(this)[0],function(){e.setCover($(a))})}}),c.attr("data-state","show"),b.endShow(c),"function"==typeof g&&g()};b.startShow(c),b.auto&&b.video&&b.video.play(),c.attr("data-state","showing"),c.attr("data-animation",d),e.setCover(c),e.curCover.push(c),e.showoverlay(f),1<e.curCover.length&&b.replace&&e.hide(e.curCover[e.curCover.length-2],d),e.curZindex++,DEVICE.isIe7?(c.stop().css({zIndex:e.curZindex,opacity:1,display:"block",marginLeft:-c.outerWidth()/2+"px",marginTop:-c.outerHeight()/2+"px"}),h()):"fade"==d?c.stop().css({zIndex:e.curZindex,opacity:1,display:"block",marginLeft:-c.outerWidth()/2+"px",marginTop:-c.outerHeight()/2+"px"}).animate({opacity:1,display:"block"},f,"swing",function(){h()}):"fadedown"==d?c.css({zIndex:e.curZindex,marginTop:-c.outerHeight()/2-150+"px",marginLeft:-c.outerWidth()/2+"px",opacity:0,display:"block"}).stop().animate({marginTop:-c.outerHeight()/2+"px",opacity:1},f,"swing",function(){h()}):"fadeup"==d?c.css({zIndex:e.curZindex,marginTop:-c.outerHeight()/2+150+"px",marginLeft:-c.outerWidth()/2+"px",opacity:0,display:"block"}).stop().animate({marginTop:-c.outerHeight()/2+"px",opacity:1},f,"swing",function(){h()}):"scale"==d&&(c.stop(),Animate.set(c,{zIndex:e.curZindex,marginTop:-c.outerHeight()/2+"px",marginLeft:-c.outerWidth()/2+"px",opacity:0,top:"50%",left:"50%",scale:.5,display:"block"}),Animate.to(c,{marginTop:-c.outerHeight()/2+"px",opacity:1,scale:1},f,"ease-in-out",function(){h()}))}//缺省obj后面的各种参数
},this.hide=function(a,c,d,f){if(!a&&0<e.curCover.length){for(var g in e.curCover)console.log(e.curCover[g]),e.hide(e.curCover[g],c,d,f);return}if("undefined"!=typeof a&&a&&"hide"!=a.attr("data-state")&&"hiding"!=a.attr("data-state")){a=$(a),"function"==typeof c&&(f=c,c=void 0),"undefined"!=typeof c&&c||("undefined"==typeof a.data("animation")?c=e.animation:c=a.data("animation")),"function"==typeof d?(f=d,d=e.time):("undefined"==typeof d||!d)&&(d=e.time),a.attr("data-state","hiding");var h=function(){a.attr("data-state","hide"),"function"==typeof f&&f(),b.video&&b.video.stop(),b.endHide(a)};for(var g in b.startHide(a),e.curZindex--,DEVICE.isIe7?(a.stop().hide(),h()):"fade"==c?a.stop().animate({opacity:0},.6*d,"swing",function(){a.css({top:"1000%"}),h()}):"fadedown"==c?a.each(function(){var a=$(this);$(this).stop().animate({marginTop:-$(this).outerHeight()/2-150+"px",opacity:0},d,"swing",function(){a.css({top:"1000%"}),h()})}):"fadeup"==c?a.each(function(){var a=$(this);$(this).stop().animate({marginTop:-$(this).outerHeight()/2+150+"px",opacity:0},d,"swing",function(){a.css({top:"1000%"}),h()})}):"scale"==c&&a.each(function(){var a=$(this);$(this).stop(),Animate.to(this,{scale:.5,opacity:0},d,"ease-in-out",function(){a.css({top:"1000%",display:"none"}),h()})}),e.hideoverlay(d),e.curCover)if(a.data("Popupcoverid")==e.curCover[g].data("Popupcoverid")){e.curCover.splice(g,1);break}}},this.showoverlay=function(a){if(!e.overclock||(clearTimeout(e.overclock),e.overclock=null),e.curZindex++,1<e.curCover.length)$("#overlay").css({zIndex:e.curZindex});else{if("none"==$("#overlay").css("display")&&$("#overlay").css({opacity:"0",display:"block"}),$("#overlay").css({zIndex:e.curZindex}),$("#overlay").stop().animate({opacity:b.opacity},a,function(){}),$("#lock").show(),!window.Popup_curhtmlOverFlow){var c=$("html").css("overflow"),d=$("body").css("overflow");window.Popup_curhtmlOverFlow=c,"hidden"!=d&&(window.Popup_curhtmlOverFlow=d)}!b.fixbody||canttouch()}},this.hideoverlay=function(a){if(e.curZindex--,!e.overclock||(clearTimeout(e.overclock),e.overclock=null),1<e.curCover.length)e.overclock=setTimeout(function(){e.overclock=null,$("#overlay").css({zIndex:e.curZindex-1})},a);else{var c=function(){$("#overlay").css({display:"none",zIndex:e.curZindex-1}),!b.fixbody||cantouch()};// if(DEVICE.isPc){
$("#overlay").stop().animate({opacity:0},a,c),$("#lock").css({overflowY:"hidden"}),$("#lock").fadeOut(a)}},this.init()}// console.log(coverEle);
};//各种需要用到的函数
function canttouch(){var a=getScrollBarWidth();a.hasscroll?($("#lock").css({overflowY:"scroll"}),$("html").css({overflow:"hidden"}),$("html").css({marginRight:a.vertical})):($("#lock").css({overflowY:"hidden",zIndex:self.curZindex}),$("html").css({overflow:"hidden"}));DEVICE.isMobile&&document.addEventListener("touchmove",touchmovePrevent,!1)}function cantouch(){$("html").css({overflow:window.Popup_curhtmlOverFlow}),$("html").css({marginRight:0});DEVICE.isMobile&&document.removeEventListener("touchmove",touchmovePrevent)}function touchmovePrevent(a){a.preventDefault()}var __scrollBarWidth=0;function getScrollBarWidth(){var a=$(window).height();if(DEVICE.isMobile||!("hidden"!=document.body.style.overflow&&"no"!=document.body.scroll&&document.body.scrollHeight>a))return{vertical:0,hasscroll:!1};if(__scrollBarWidth)return __scrollBarWidth;var b=document.createElement("div");// if MSIE
// 如此设置的话，scroll bar的最大宽度不能大于100px（通常不会）。
return b.style.cssText="overflow:scroll;width:100px;height:100px;",document.body.appendChild(b),b&&(__scrollBarWidth={horizontal:b.offsetHeight-b.clientHeight,vertical:b.offsetWidth-b.clientHeight,hasscroll:!0}),document.body.removeChild(b),__scrollBarWidth}function _defineProperty(a,b,c){return b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}_defineProperty(Popup,"plugin",function(a){return!a||!a.fn||function(a){a.fn.fPopup=function(a){return new Popup($(this),a)}}(a),Popup});export default Popup;
