import $ from"jquery";window.JSON||(window.JSON={parse:function(jsonStr){return eval("("+jsonStr+")")},stringify:function(a){var b,c="";if(null===a)return a+"";switch(typeof a){case"number":case"boolean":return a+"";case"string":return"\""+a+"\"";case"undefined":case"function":return;}switch(Object.prototype.toString.call(a)){case"[object Array]":c+="[";for(var d=0,e=a.length;d<e;d++)b=JSON.stringify(a[d]),c+=(void 0===b?null:b)+",";return"["!==c&&(c=c.slice(0,-1)),c+="]",c;case"[object Date]":return"\""+(a.toJSON?a.toJSON():a.toString())+"\"";case"[object RegExp]":return"{}";case"[object Object]":for(d in c+="{",a)a.hasOwnProperty(d)&&(b=JSON.stringify(a[d]),void 0!==b&&(c+="\""+d+"\":"+b+","));return"{"!==c&&(c=c.slice(0,-1)),c+="}",c;case"[object String]":return"\""+a.toString()+"\"";case"[object Number]":case"[object Boolean]":return a.toString();}}});var Utli={log:function(a){this.isdev()||!window.console||console.log(a)},query:function(a){"string"==typeof a&&(a=$(a));// console.log(str + "");
var b=!!a&&!!a.__proto__&&!!a.__proto__.jquery;if(b){var c=[];//console.log(res);
return 1<a.length?a.each(function(){c.push(this)}):c=a[0],c}return a},isZtgameDev:function(){//是否是测试环境
var a=window.location.host;return-1<a.indexOf("web.ztgame.com")||-1<a.indexOf("dev.ztgame.com")||"localhost"==a},setIframeHeight:function(){},isdev:function(){//是否是测试环境
var a=window.location.host;return-1<a.indexOf("web.ztgame.com")||-1<a.indexOf("dev.ztgame.com")||"localhost"==a},getJsPath:function(a){//获取引入js的路径
var b=/^(.+\.)?(web|dev)\.ztgame/.test(location.host)?"//siteres.dev.ztgame.com/site/dist/":"//siteres.ztgame.com/site/js/",c=b+a;return c.substring(0,c.lastIndexOf("/")+1)},isNaN:function(a){var b=/^[\d]+$/;return b.test(a)},jsonToUrl:function(a){var b,c="";if(!!a&&"object"==typeof a)for(var d in a)b=typeof a[d],"object"===b?a[d]=JSON.stringify(a[d]):void 0,!c||(c+="&"),c+=d+"="+a[d];// if (!!url) {
//     url = encodeURIComponent(url);
// }
return c},getParam:function(a){//获取url中的 参数
var b=new RegExp("(^|&)"+a+"=([^&]*)(&|$)"),c=window.location.search.substr(1).match(b);return null==c?null:unescape(c[2])},getAllParams:function(){//获取search 所有参数
var a,b={},c=window.location.search.replace("?",""),d=c.split("&");if(!!d&&"object"==typeof d)for(var e in d)d[e]&&(a=d[e].split("="),!a||!a[0]||(a[1]?("true"==a[1]&&(a[1]=!0),"false"==a[1]&&(a[1]=!1),("null"==a[1]||"undefined"==a[1])&&(a[1]=null),b[a[0]]=a[1]):b[a[0]]=""));return b}};export default Utli;
